# **Install & Import Required Libraries**

In [ ]:
# Install & Import Required Libraries

import pandas as pd
import sqlite3

# **Extract Phase**

**Load Datasets**

In [ ]:
# Load Datasets

cases = pd.read_csv(
    "/content/covid_19_india.csv"
)

vaccine = pd.read_csv(
    "/content/covid_vaccine_statewise.csv"
)

testing = pd.read_csv(
    "/content/StatewiseTestingDetails.csv"
)

**Create SQL Database**

In [ ]:
# Create SQL Database

conn = sqlite3.connect("covid.db")

**Load Data into SQL Tables**

In [ ]:
# Load Data into SQL Tables

cases.to_sql("covid_cases", conn, if_exists="replace", index=False)
vaccine.to_sql("covid_vaccination", conn, if_exists="replace", index=False)
testing.to_sql("covid_testing", conn, if_exists="replace", index=False)

16336

**Inspect covid_cases Data**

In [ ]:
# Inspect covid_cases Data

pd.read_sql("SELECT COUNT(*) FROM covid_cases", conn)
pd.read_sql("SELECT * FROM covid_cases LIMIT 10", conn)

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3
5,6,2020-02-04,6:00 PM,Kerala,3,0,0,0,3
6,7,2020-02-05,6:00 PM,Kerala,3,0,0,0,3
7,8,2020-02-06,6:00 PM,Kerala,3,0,0,0,3
8,9,2020-02-07,6:00 PM,Kerala,3,0,0,0,3
9,10,2020-02-08,6:00 PM,Kerala,3,0,0,0,3

**Inspect covid_vaccination Data**

In [ ]:
# Inspect covid_vaccination Data

pd.read_sql("SELECT COUNT(*) FROM covid_vaccination", conn)
pd.read_sql("SELECT * FROM covid_vaccination LIMIT 10", conn)

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,None,None,None,...,None,None,None,None,None,None,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,None,None,None,...,None,None,None,None,None,None,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,None,None,None,...,None,None,None,None,None,None,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,None,None,None,...,None,None,None,None,None,None,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,None,None,None,...,None,None,None,None,None,None,98111.0,153145.0,24.0,251280.0
5,21/01/2021,India,365965.0,32226.0,12600.0,365965.0,0.0,None,None,None,...,None,None,None,None,None,None,132784.0,233143.0,38.0,365965.0
6,22/01/2021,India,549381.0,36988.0,14115.0,549381.0,0.0,None,None,None,...,None,None,None,None,None,None,193899.0,355402.0,80.0,549381.0
7,23/01/2021,India,759008.0,43076.0,15605.0,759008.0,0.0,None,None,None,...,None,None,None,None,None,None,267856.0,491049.0,103.0,759008.0
8,24/01/2021,India,835058.0,49851.0,18111.0,835058.0,0.0,None,None,None,...,None,None,None,None,None,None,296283.0,538647.0,128.0,835058.0
9,25/01/2021,India,1277104.0,55151.0,19682.0,1277104.0,0.0,None,None,None,...,None,None,None,None,None,None,444137.0,832766.0,201.0,1277104.0

**Inspect covid_testing Data**

In [ ]:
# Inspect covid_testing Data

pd.read_sql("SELECT COUNT(*) FROM covid_testing", conn)
pd.read_sql("SELECT * FROM covid_testing LIMIT 10", conn)

         Date                        State  TotalSamples Negative  Positive
0  2020-04-17  Andaman and Nicobar Islands        1403.0     1210      12.0
1  2020-04-24  Andaman and Nicobar Islands        2679.0     None      27.0
2  2020-04-27  Andaman and Nicobar Islands        2848.0     None      33.0
3  2020-05-01  Andaman and Nicobar Islands        3754.0     None      33.0
4  2020-05-16  Andaman and Nicobar Islands        6677.0     None      33.0
5  2020-05-19  Andaman and Nicobar Islands        6965.0     None      33.0
6  2020-05-20  Andaman and Nicobar Islands        7082.0     None      33.0
7  2020-05-21  Andaman and Nicobar Islands        7167.0     None      33.0
8  2020-05-22  Andaman and Nicobar Islands        7263.0     None      33.0
9  2020-05-23  Andaman and Nicobar Islands        7327.0     None      33.0

**DISTINCT STATES CHECK**

In [ ]:
# DISTINCT STATES CHECK

pd.read_sql("""
SELECT DISTINCT State FROM covid_vaccination
""", conn)

                                       State
0                                      India
1                Andaman and Nicobar Islands
2                             Andhra Pradesh
3                          Arunachal Pradesh
4                                      Assam
5                                      Bihar
6                                 Chandigarh
7                               Chhattisgarh
8   Dadra and Nagar Haveli and Daman and Diu
9                                      Delhi
10                                       Goa
11                                   Gujarat
12                                   Haryana
13                          Himachal Pradesh
14                         Jammu and Kashmir
15                                 Jharkhand
16                                 Karnataka
17                                    Kerala
18                                    Ladakh
19                               Lakshadweep
20                            Madhya Pradesh
21                               Maharashtra
22                                   Manipur
23                                 Meghalaya
24                                   Mizoram
25                                  Nagaland
26                                    Odisha
27                                Puducherry
28                                    Punjab
29                                 Rajasthan
30                                    Sikkim
31                                Tamil Nadu
32                                 Telangana
33                                   Tripura
34                             Uttar Pradesh
35                               Uttarakhand
36                               West Bengal

**NULL CHECKS**

In [ ]:
# NULL CHECKS

pd.read_sql("""
SELECT COUNT(*) AS null_confirmed
FROM covid_cases
WHERE Confirmed IS NULL OR Deaths IS NULL
""", conn)

   null_confirmed
0               0

# **Transform Phase**

**Standardize Date Format**

In [ ]:
# Standardize Date Format

pd.read_sql("""
SELECT
    DATE(Date) AS date,
    "State/UnionTerritory" AS state,
    Confirmed,
    Deaths
FROM covid_cases
""", conn)

             date          state  Confirmed  Deaths
0      2020-01-30         Kerala          1       0
1      2020-01-31         Kerala          1       0
2      2020-02-01         Kerala          2       0
3      2020-02-02         Kerala          3       0
4      2020-02-03         Kerala          3       0
...           ...            ...        ...     ...
18105  2021-08-11      Telangana     650353    3831
18106  2021-08-11        Tripura      80660     773
18107  2021-08-11    Uttarakhand     342462    7368
18108  2021-08-11  Uttar Pradesh    1708812   22775
18109  2021-08-11    West Bengal    1534999   18252

[18110 rows x 4 columns]

**Daily New Cases**

In [ ]:
# Daily New Cases

pd.read_sql("""
SELECT
    state,
    date,
    Confirmed -
    LAG(Confirmed) OVER (PARTITION BY state ORDER BY date)
    AS Daily_New_Cases
FROM (
    SELECT
        DATE(Date) AS date,
        "State/UnionTerritory" AS state,
        Confirmed
    FROM covid_cases
)
""", conn)

                             state        date  Daily_New_Cases
0      Andaman and Nicobar Islands  2020-03-26              NaN
1      Andaman and Nicobar Islands  2020-03-27              0.0
2      Andaman and Nicobar Islands  2020-03-28              5.0
3      Andaman and Nicobar Islands  2020-03-29              3.0
4      Andaman and Nicobar Islands  2020-03-30              0.0
...                            ...         ...              ...
18105                  West Bengal  2021-08-07            717.0
18106                  West Bengal  2021-08-08            749.0
18107                  West Bengal  2021-08-09            675.0
18108                  West Bengal  2021-08-10            557.0
18109                  West Bengal  2021-08-11            639.0

[18110 rows x 3 columns]

**Total Confirmed (Indian + Foreign)**

In [ ]:
# Total Confirmed (Indian + Foreign)

pd.read_sql("""
SELECT
    state,
    date,
    (ConfirmedIndianNational + ConfirmedForeignNational) AS Total_Confirmed
FROM (
    SELECT
        DATE(Date) AS date,
        "State/UnionTerritory" AS state,
        ConfirmedIndianNational,
        ConfirmedForeignNational
    FROM covid_cases
)
""", conn)

               state        date  Total_Confirmed
0             Kerala  2020-01-30                1
1             Kerala  2020-01-31                1
2             Kerala  2020-02-01                2
3             Kerala  2020-02-02                3
4             Kerala  2020-02-03                3
...              ...         ...              ...
18105      Telangana  2021-08-11                0
18106        Tripura  2021-08-11                0
18107    Uttarakhand  2021-08-11                0
18108  Uttar Pradesh  2021-08-11                0
18109    West Bengal  2021-08-11                0

[18110 rows x 3 columns]

**Case Fatality Rate**

In [ ]:
# Case Fatality Rate

pd.read_sql("""
SELECT
    state,
    date,
    ROUND((Deaths * 100.0 / Confirmed), 2) AS CFR
FROM (
    SELECT
        DATE(Date) AS date,
        "State/UnionTerritory" AS state,
        Confirmed,
        Deaths
    FROM covid_cases
)
WHERE Confirmed > 0
""", conn)

               state        date   CFR
0             Kerala  2020-01-30  0.00
1             Kerala  2020-01-31  0.00
2             Kerala  2020-02-01  0.00
3             Kerala  2020-02-02  0.00
4             Kerala  2020-02-03  0.00
...              ...         ...   ...
18059      Telangana  2021-08-11  0.59
18060        Tripura  2021-08-11  0.96
18061    Uttarakhand  2021-08-11  2.15
18062  Uttar Pradesh  2021-08-11  1.33
18063    West Bengal  2021-08-11  1.19

[18064 rows x 3 columns]

**Join Cases + Testing**

In [ ]:
# Join Cases + Testing

pd.read_sql("""
SELECT
    c.state,
    c.date,
    c.Confirmed,
    t.TotalSamples,
    t.Positive
FROM (
    SELECT DATE(Date) AS date,
           "State/UnionTerritory" AS state,
           Confirmed
    FROM covid_cases
) c
JOIN covid_testing t
ON c.state = t.State AND c.date = DATE(t.Date)
""", conn)

                state        date  Confirmed  TotalSamples  Positive
0               Delhi  2020-04-01        152        2621.0       NaN
1              Kerala  2020-04-01        241        7965.0     265.0
2         West Bengal  2020-04-01         37         659.0      37.0
3      Andhra Pradesh  2020-04-02         86        1800.0     132.0
4               Assam  2020-04-02          5         962.0      16.0
...               ...         ...        ...           ...       ...
15934       Telangana  2021-08-10     649859    22991849.0       NaN
15935         Tripura  2021-08-10      80416     1630572.0   80413.0
15936     Uttarakhand  2021-08-10     342423     6526861.0       NaN
15937   Uttar Pradesh  2021-08-10    1708793    67897856.0       NaN
15938     West Bengal  2021-08-10    1534360    16162814.0       NaN

[15939 rows x 5 columns]

# **Load Phase**

**Drop existing table**

In [ ]:
# Drop existing table
conn.execute("DROP TABLE IF EXISTS covid_summary")
conn.commit()

conn.execute("DROP TABLE IF EXISTS vacc_clean")
conn.commit()

**Create Table vacc_clean**

In [ ]:
# Create Table vacc_clean

conn.execute("""
CREATE TABLE vacc_clean AS
SELECT
    UPPER(TRIM(State)) AS state,

    -- Convert DD/MM/YYYY → YYYY-MM-DD
    SUBSTR("Updated On", 7, 4) || '-' ||
    SUBSTR("Updated On", 4, 2) || '-' ||
    SUBSTR("Updated On", 1, 2) AS date,

    MAX(COALESCE("First Dose Administered", 0))  AS First_Dose,
    MAX(COALESCE("Second Dose Administered", 0)) AS Second_Dose

FROM covid_vaccination
GROUP BY state, date;

""")

conn.commit()

**Verify table vacc_clean**

In [ ]:
# Verify table vacc_clean

pd.read_sql("SELECT * FROM vacc_clean", conn)

                            state        date  First_Dose  Second_Dose
0     ANDAMAN AND NICOBAR ISLANDS  2021-01-16        23.0          0.0
1     ANDAMAN AND NICOBAR ISLANDS  2021-01-17        23.0          0.0
2     ANDAMAN AND NICOBAR ISLANDS  2021-01-18        42.0          0.0
3     ANDAMAN AND NICOBAR ISLANDS  2021-01-19        89.0          0.0
4     ANDAMAN AND NICOBAR ISLANDS  2021-01-20       124.0          0.0
...                           ...         ...         ...          ...
7840                  WEST BENGAL  2021-08-11         0.0          0.0
7841                  WEST BENGAL  2021-08-12         0.0          0.0
7842                  WEST BENGAL  2021-08-13         0.0          0.0
7843                  WEST BENGAL  2021-08-14         0.0          0.0
7844                  WEST BENGAL  2021-08-15         0.0          0.0

[7845 rows x 4 columns]

**Create Table covid_summary**

In [ ]:
# Create Table covid_summary

conn.execute("""
CREATE TABLE covid_summary AS
SELECT
    c.state,
    c.date,
    c.Confirmed,
    c.Deaths,
    c.Cured,
    c.Daily_New_Cases,
    t.TotalSamples,
    t.Positive,

    COALESCE(v.First_Dose, 0)  AS First_Dose,
    COALESCE(v.Second_Dose, 0) AS Second_Dose,

    ROUND(
        CASE WHEN c.Confirmed > 0
        THEN (c.Deaths * 100.0 / c.Confirmed)
        ELSE 0 END, 2
    ) AS CFR,

    ROUND(
        CASE WHEN t.TotalSamples > 0
        THEN (t.Positive * 100.0 / t.TotalSamples)
        ELSE 0 END, 2
    ) AS Positive_Rate

FROM (
    SELECT
        DATE(Date) AS date,
        UPPER(TRIM("State/UnionTerritory")) AS state,
        Confirmed,
        Deaths,
        Cured,
        Confirmed -
        LAG(Confirmed) OVER (
            PARTITION BY UPPER(TRIM("State/UnionTerritory"))
            ORDER BY DATE(Date)
        ) AS Daily_New_Cases
    FROM covid_cases
) c

LEFT JOIN covid_testing t
    ON UPPER(TRIM(t.State)) = c.state
   AND DATE(t.Date) = c.date

LEFT JOIN vacc_clean v
    ON v.state = c.state
   AND v.date = c.date;
""")

conn.commit()

**Verify table covid_summary**

In [ ]:
# Verify table covid_summary

pd.read_sql("SELECT * FROM covid_summary", conn)

,state,date,Confirmed,Deaths,Cured,Daily_New_Cases,TotalSamples,Positive,First_Dose,Second_Dose,CFR,Positive_Rate
0,ANDAMAN AND NICOBAR ISLANDS,2020-03-26,1,0,0,NaN,NaN,NaN,0.0,0.0,0.00,0.0
1,ANDAMAN AND NICOBAR ISLANDS,2020-03-27,1,0,0,0.0,NaN,NaN,0.0,0.0,0.00,0.0
2,ANDAMAN AND NICOBAR ISLANDS,2020-03-28,6,0,0,5.0,NaN,NaN,0.0,0.0,0.00,0.0
3,ANDAMAN AND NICOBAR ISLANDS,2020-03-29,9,0,0,3.0,NaN,NaN,0.0,0.0,0.00,0.0
4,ANDAMAN AND NICOBAR ISLANDS,2020-03-30,9,0,0,0.0,NaN,NaN,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
18106,WEST BENGAL,2021-08-07,1532379,18202,1503535,717.0,16045662.0,NaN,22959053.0,9070272.0,1.19,NaN
18107,WEST BENGAL,2021-08-08,1533128,18217,1504326,749.0,16092192.0,NaN,23017864.0,9080904.0,1.19,NaN
18108,WEST BENGAL,2021-08-09,1533803,18229,1505089,675.0,16122345.0,NaN,23257417.0,9132961.0,1.19,NaN
18109,WEST BENGAL,2021-08-10,1534360,18240,1505808,557.0,16162814.0,NaN,0.0,0.0,1.19,NaN
18110,WEST BENGAL,2021-08-11,1534999,18252,1506532,639.0,NaN,NaN,0.0,0.0,1.19,0.0

**Risk Level Column**

In [ ]:
# Risk Level Column

final_df = pd.read_sql("""
SELECT *,
CASE
    WHEN CFR > 2 AND Positive_Rate > 10 THEN 'High'
    WHEN CFR > 2 OR Positive_Rate > 10 THEN 'Medium'
    ELSE 'Low'
END AS Risk_Level
FROM covid_summary
""", conn)

final_df

,state,date,Confirmed,Deaths,Cured,Daily_New_Cases,TotalSamples,Positive,First_Dose,Second_Dose,CFR,Positive_Rate,Risk_Level
0,ANDAMAN AND NICOBAR ISLANDS,2020-03-26,1,0,0,NaN,NaN,NaN,0.0,0.0,0.00,0.0,Low
1,ANDAMAN AND NICOBAR ISLANDS,2020-03-27,1,0,0,0.0,NaN,NaN,0.0,0.0,0.00,0.0,Low
2,ANDAMAN AND NICOBAR ISLANDS,2020-03-28,6,0,0,5.0,NaN,NaN,0.0,0.0,0.00,0.0,Low
3,ANDAMAN AND NICOBAR ISLANDS,2020-03-29,9,0,0,3.0,NaN,NaN,0.0,0.0,0.00,0.0,Low
4,ANDAMAN AND NICOBAR ISLANDS,2020-03-30,9,0,0,0.0,NaN,NaN,0.0,0.0,0.00,0.0,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18106,WEST BENGAL,2021-08-07,1532379,18202,1503535,717.0,16045662.0,NaN,22959053.0,9070272.0,1.19,NaN,Low
18107,WEST BENGAL,2021-08-08,1533128,18217,1504326,749.0,16092192.0,NaN,23017864.0,9080904.0,1.19,NaN,Low
18108,WEST BENGAL,2021-08-09,1533803,18229,1505089,675.0,16122345.0,NaN,23257417.0,9132961.0,1.19,NaN,Low
18109,WEST BENGAL,2021-08-10,1534360,18240,1505808,557.0,16162814.0,NaN,0.0,0.0,1.19,NaN,Low
18110,WEST BENGAL,2021-08-11,1534999,18252,1506532,639.0,NaN,NaN,0.0,0.0,1.19,0.0,Low

**Export for Excel**

In [ ]:
# Export for Excel

#final_df = pd.read_sql("SELECT * FROM covid_summary", conn)
final_df.to_csv("covid_summary.csv", index=False)

**CSV File (covid_summary.csv) is ready to dwonload for Excel Analysis.**